Repository parthoCarleton/Group_C_ipsiFramework, pull requests merged in 2020-11, with the labels that each got.

#34 Added ipsiConnectionType() function
  ipsi/bin/libipsi.so
  ipsi/obj/libipsi.o
  ipsi/src/ipsi.c
Labels: enhancement

#40 UT for ipsiMethodCall
  ipsiTest/ut_test/Makefile
  ipsiTest/ut_test/unitTest_ipsiMethodCall_UT.c
Labels: Testing

#43 Added IPSI register function + .gitignore was modified
  .gitignore
  ipsi/bin/libipsi.so
  ipsi/obj/libipsi.o
  ipsi/src/ipsi.c
Labels: enhancement

#48 Dev deepti
  ipsiTest/ut_test/Makefile
  ipsiTest/ut_test/unitTest_ipsiRegisterFunction_UT.c
Labels: Testing

#49 Added ipsiListen
  ipsiTest/ut_test/Makefile
  ipsiTest/ut_test/unitTest_ipsiListen_UT.c
Labels: Testing

#47 added isServer() to ipsi source file
  ipsi/src/ipsi.c
Labels: enhancement

#50 adding isCaller() function in source file
  ipsi/src/ipsi.c
Labels: enhancement

#53 modified function initConnectionName
  ipsi/src/ipsi.c
Labels: enhancement

#56 added unit tests for isCaller()
  ipsiTest/ut_test/Makefile
  ipsiTest/ut_test/unitTest_isCaller_UT.c
Labels: Testing

#58 Bug fix- handle ipsiConnectionType failure
  .gitignore
  ipsi/bin/.gitignore
  ipsi/obj/.gitignore
  ipsi/src/ipsi.c
  ipsiTest/runUT.sh
  ipsiTest/ut_test/Makefile
  ipsiTest/ut_test/unitTest_ipsiConnectionType_UT.c
  ipsiTest/ut_test/unitTest_ipsiListen_UT.c
  ipsiTest/ut_test/unitTest_ipsiMethodCall_UT.c
  ipsiTest/ut_test/unitTest_isServer_UT.c
Labels: bug

#60 Fixed Programming Style Guidelines + Updated compilation Flags
  ipsi/Makefile
  ipsi/inc/ipsi.h
  ipsi/src/ipsi.c
  ipsiTest/ut_test/stub_UT.c
  ipsiTest/ut_test/unitTest_ipsiConnectionType_UT.c
  ipsiTest/ut_test/unitTest_ipsiListen_UT.c
  ipsiTest/ut_test/unitTest_ipsiMethodCall_UT.c
  ipsiTest/ut_test/unitTest_ipsiRegisterFunction_UT.c
  ipsiTest/ut_test/unitTest_isCaller_UT.c
  ipsiTest/ut_test/unitTest_isServer_UT.c
Labels: programming style
